controllers/CardController.php
<?php
namespace app\controllers;

use app\modules\menu\actions\DownloadFileAction;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Card;
use app\models\CashFlow;
use app\models\search\CashFlowSearch;
use yii\helpers\ArrayHelper;


/**
 * Site controller
 */
class CardController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'download'=>[
                'class'=>DownloadFileAction::className()
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionAdd($id)
    {
        $model = new CashFlow();

        //Yii::$app->user->identity->getId();

        if( $model->load(Yii::$app->request->post()) ){
            $model->sender = Card::getDefaultCard()->id;
            $model->recipient = $id;

            //echo "<pre>"; var_dump($model); echo "</pre>";
            if( $model->save() ){
                return $this->render('../site/requestWindowInner',[
                    'title' => 'Счет пополнен',
                    'text' => 'Для пополнения не требуется  ввод pin-кода',
                    'link' => '/',
                    'class' => 'registrated',
                    'linkText' => 'Ок',
                ]);
            }
        }

        return $this->render('add', [
            'model' => $model,
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionMinus($id)
    {
        $model = new CashFlow();
        $card = new Card();
        $error = false;
        //Yii::$app->user->identity->getId();

        if( $model->load(Yii::$app->request->post()) && $card->load(Yii::$app->request->post()) ){
            // TO-DO при рефакторинге сделать агрегированный метод проверок по карте с выдачей ошибок
            // TO-DO сделать в моделе метод перевода средств между картами
            if( Card::isThisUserCard($id, Yii::$app->user->identity->getId()) )
            {
                if( Card::checkPinByCard($id, $card->pass) )
                {
                    $model->sender = $id;
                    $model->recipient = Card::getDefaultCard()->id;

                    $total = CashFlow::getTotalByCard($id);
                    if ($total) {
                        $minus = $model->sum;
                        $afterTotal = $total["total"] - $minus;

                        if ($afterTotal > 0 || $afterTotal === 0) {
                            if ($model->save()) {
                                return $this->render('../site/requestWindowInner', [
                                    'title' => 'Со счета сняты деньги',
                                    'text' => '',
                                    'link' => '/',
                                    'class' => 'registrated',
                                    'linkText' => 'Ок',
                                ]);
                            }
                        }
                        else $error = 'Недостаточно средств. Баланс: ' . $total["total"] . '$';
                    }
                    else $error = 'Недостаточно средств';
                }
                else $error = 'Неверный pin';
            }
            else $error = 'Вы не являетесь владельцем карты';
        }

        return $this->render('minus', [
            'model' => $model,
            'error' => $error,
            'card' => $card,
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionHistory($id)
    {
        $searchModel = new CashFlowSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $id);

        return $this->render('history', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionSend($id)
    {
        $model = new CashFlow();
        $card = new Card();
        $error = false;
        //Yii::$app->user->identity->getId();

        if( $model->load(Yii::$app->request->post()) && $card->load(Yii::$app->request->post()) ){
            // TO-DO при рефакторинге сделать агрегированный метод проверок по карте с выдачей ошибок
            // TO-DO сделать в моделе метод перевода средств между картами
            if( Card::isThisUserCard($id, Yii::$app->user->identity->getId()) )
            {
                if( Card::checkPinByCard($id, $card->pass) )
                {
                    $model->sender = $id;
                    $model->recipient = $card->card_number;

                    $total = CashFlow::getTotalByCard($id);
                    if ($total) {
                        $minus = $model->sum;
                        $afterTotal = $total["total"] - $minus;

                        if ($afterTotal > 0 || $afterTotal === 0) {
                            if ($model->save()) {
                                return $this->render('../site/requestWindowInner', [
                                    'title' => 'Деньги переведены',
                                    'text' => '',
                                    'link' => '/',
                                    'class' => 'registrated',
                                    'linkText' => 'Ок',
                                ]);
                            }
                        }
                        else $error = 'Недостаточно средств. Баланс: ' . $total["total"] . '$';
                    }
                    else $error = 'Недостаточно средств';
                }
                else $error = 'Неверный pin';
            }
            else $error = 'Вы не являетесь владельцем карты';
        }

        $cardList = ArrayHelper::map(Card::find()->where(['<>', 'id', $id])->all(),'id','card_number');

        return $this->render('send', [
            'model' => $model,
            'error' => $error,
            'card' => $card,
            'cardList' => $cardList,
        ]);
    }
}

controllers/SiteController.php
<?php
namespace app\controllers;

use app\models\User;
use app\modules\menu\actions\DownloadFileAction;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\UserProfile;
use app\models\forms\SignupForm;
use app\models\search\CardSearch;
use app\models\Card;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'except' => [
                    'signup', 'signin', 'preloader', 'download', 'bug-messages', 'request-password-reset',
                ],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'download'=>[
                'class'=>DownloadFileAction::className()
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CardSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $card_number = randString( 16, array("0123456789"));
        $pin = randString( 4, array("0123456789"));

        $card = Card::findOne(['card_number'=>$card_number]);
        while( $card ){
            $card_number = randString( 16, array("0123456789"));
            $card = Card::findOne(['card_number'=>$card_number]);
        }

        $card = new Card();
        $card->user_id = Yii::$app->user->identity->getId();
        $card->card_number = $card_number;
        $card->month = rand( 1, 12);
        $card->year = 2020;
        $card->pin = Yii::$app->security->generatePasswordHash($pin);
        $card->save();

        return $this->render('requestWindowInner',[
            'title' => 'PIN-код: '.$pin.' Номер карты: '.$card->card_number,
            'text' => 'Обычно здесь шлеться письмо на почту пользователю. Упрощаем этот шаг и показываем здесь.',
            'link' => '/',
            'class' => 'registrated',
            'linkText' => 'Ок',
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionPreloader()
    {
        $this->layout = 'dark';
        return $this->render('preloader');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionSignin()
    {
        $this->layout = 'dark';

        if (!Yii::$app->user->isGuest) {
            $this->redirect('/');
            //return 'You are already sign in';
        }

        $model = new LoginForm();
        if( $model->load(Yii::$app->request->post()) ) {

            if( $model->validate() && $model->login() ){

                $this->redirect('/');
            }else{

                $errorCopy = $model->errors;
                $errorStr = array_shift($errorCopy)[0];

                return $this->render('requestWindow',[
                    'title' => 'Ошибка!',
                    'text' => $errorStr,
                    'link' => '/signin'
                ]);
            }

        } else {

            $model->password = '';
            return $this->render('signin', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout = 'dark';

        if (!Yii::$app->user->isGuest) {
            $this->redirect('/');
        }

        $model = new SignupForm();
        $profile = new UserProfile();

        if ($model->load(Yii::$app->request->post())) {

            $signupRes = $model->signup();

            if( count($model->errors) ) {

                return $this->render('requestWindow', [
                    'title' => array_shift($model->errors),
                    'text' => 'Пожалуйста, проверьте корректность данных или обратитесь в службу поддержки',
                    'link' => '/signup',
                    'class' => 'vin',
                ]);

            }else {

                return $this->render('requestWindow',[
                    'title' => 'Пароль: 123456789',
                    'text' => 'Обычно здесь шлеться письмо с ссылкой для активации учетной записи и установки пароля из кабинета. 
                        Так как возможны проблемы отсылки почтовых сообщений в связи с правилами политики безопасности компаниии
                        - упрощаем этот шаг',
                    'link' => '/',
                    'class' => 'registrated',
                ]);

            }
        }

        $profile->gender = $profile::GENDER_MALE;

        return $this->render('signup', [
            'model' => $model,
            'profile' => $profile,
            'mError' => $model->errors,
        ]);
    }

    public function actionBugMessages()
    {
        $this->layout = 'dark';

        return $this->render('requestWindow',[
            'title' => 'Обычно здесь форма обратной связи.',
            'text' => 'В рамках данной задачи она отсутствует.',
            'link' => '/',
            'class' => 'bug-messages',
        ]);

    }

    public function actionRequestPasswordReset()
    {
        $this->layout = 'dark';

        return $this->render('requestWindow',[
            'title' => 'Обычно здесь форма сброса пароля.',
            'text' => 'Функциональность убрана в связи с возможным отсутствием возможности почтовых рассылок',
            'link' => '/',
            'class' => 'bug-messages',
        ]);

    }

}

views/site/bugMessages.php
<?php

/* @var $this yii\web\View */
/* @var $form \yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use app\models\LoginForm;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\web\JsExpression;
use yii\web\View;

$this->title = 'Не удается войти?';
?>
<div class="preload-wrapper">
    <div class="backgrond"></div>

    <div class="pl-topper light">
        <div class="container">
            <div class="row">
                <div class="col-12 text-right">
                    <div class="logo">
                        <a href="/" class="ls-wrapper">
                            <img src="/image/TransLoyd/logo1.png">
                            <div class="slogan">Trans Loyd</div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="site-bug-messages">
        <div class="row">

            <div class="col-lg-12">
                <div class="title">Не удается войти?</div>

                <div class="text">
                    Оставьте данные и опишите проблему. <br>
                    Оператор свяжется с вами.
                </div>
            </div>

            <div class="col-lg-12">
                <?php $form = ActiveForm::begin([
                    'id' => 'bugMessages',
                    'fieldConfig' => ['enableLabel'=>false],
                    'options'=>['data-window-id' => "bugMessages", 'autocomplete' => "off"],
                    'validateOnBlur' => false,
                ]); ?>

                <div class="row">
                    <div class="col-12 col-md-6 mb-4">
                        <?= $form->field($model, 'name')->textInput(['placeholder' => $model->attributeLabels()['name']]);?>
                    </div>

                    <div class="col-12 col-md-6 mb-4">
                        <?= $form->field($model, 'phone')->textInput(['placeholder' => $model->attributeLabels()['phone'],'class' => 'form-control phone-mask']);?>
                    </div>

                    <div class="col-12 mb-4">
                        <?= $form->field($model, 'problem')->textInput(['placeholder' => $model->attributeLabels()['problem'],'maxlength' => 500]);?>
                    </div>

                    <div class="col-md-6 col-12 mb-4">
                        <?= $form->field($model, 'picture')->widget(
                            \trntv\filekit\widget\Upload::className(),
                            [
                                'url' => ['/file-storage/upload'],
                                'maxFileSize' => 5*1024*1024, // 5 MiB
                                'acceptFileTypes' => new JsExpression('/(\.|\/)(gif|jpe?g|png)$/i'),
                                'showPreviewFilename' => true,
                            ]);
                        ?>

                        <?//= $form->field($model, 'screen')->fileInput(['placeholder' => $model->attributeLabels()['screen'], 'class' => 'form-control file-icon']);?>

                        <!--div class="form-group field-userprofile-firstname required validating file-icon">
                            <input type="text" id="userprofile-firstname" class="form-control" name="UserProfile[firstname]" placeholder="Скриншот" aria-required="true" aria-invalid="true">
                            <div class="invalid-feedback"></div>
                        </div-->
                    </div>
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'smb-btn']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>

        </div>
    </div>
</div>

views/site/callback.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'Восстановление пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="preload-wrapper">
    <div class="site-callback">
        <div class="row">
            <div class="col-lg-12">
                <div class="title">Обратная связь</div>

                <div class="text">
                    Телефон: 8 800 600-03-03 <br>
                    E-mail: excellence-club@bmw.com
                </div>

                <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                    <?= $form->field($model, 'text')->textarea(['maxlength'=>500])->label('Напишите нам');?>

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'smb-btn'])?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>

</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\bootstrap4\ActiveForm;
use kartik\grid\GridView;
use yii\helpers\Html;

$this->title = 'TRANS LOYD';
$url = $systemReference->picture['base_url'].$systemReference->picture['path'];
?>

<div class="ti-text-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">
                Описание: так как проект не продпалагает эксплуатации, то в результате разработки были допущены
                некоторые упрощения, а именно:
                <br>
                <ul>
                    <li>
                        В действительности номер карты и номер счет хранения средств это разные сущности, именно
                        это позволяет к одному счету привязывать несколько карт. Но так как такой
                        задачи не было - упрощаем и делаем № банковской карты = № номеру
                    </li>
                    <li>
                        Финансовые учереждения практикуют использовать для ведения учета принцип двойной записи,
                        перемещая средства между счетами корреспондентами. А так как мы заменили № счета на №
                        банковских карт, для внесения и вывода средств будет использоваться спец. карта,
                        предварительно созданная для этого.
                    </li>
                </ul>
            </div>

            <div class="col-12">
                <?
                $columns = [
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template'=>'{add} {minus} {history} {send}',
                        'buttons' => [
                            'add' => function ($url, $model, $key) {
                                $url = \yii\helpers\Url::to(['card/add', 'id' => $model['id']]);

                                $iconName = "plus";
                                $icon = Html::tag('span', '', ['class' => "glyphicon glyphicon-$iconName"]);

                                return Html::a($icon, $url,['title'=>'Положить деньги на карту']);

                            },

                            'minus' => function ($url, $model, $key) {
                                $url = \yii\helpers\Url::current(['card/minus', 'id' => $model['id']]);

                                $iconName = "minus";
                                $icon = Html::tag('span', '', ['class' => "glyphicon glyphicon-$iconName"]);

                                return Html::a($icon, $url,['title'=>'Снять деньги c карты']);
                            },

                            'history' => function ($url, $model, $key) {
                                $url = \yii\helpers\Url::to(['card/history', 'id' => $model['id']]);

                                $iconName = "search";
                                $icon = Html::tag('span', '', ['class' => "glyphicon glyphicon-$iconName"]);

                                return Html::a($icon, $url,['title'=>'Движение средств по карте']);

                            },

                            'send' => function ($url, $model, $key) {
                                $url = \yii\helpers\Url::current(['card/send', 'id' => $model['id']]);

                                $iconName = "envelope";
                                $icon = Html::tag('span', '', ['class' => "glyphicon glyphicon-$iconName"]);

                                return Html::a($icon, $url,['title'=>'Перевести средства']);

                            },
                        ],
                    ],
                    [
                        'attribute'=>'id',
                        'format'=>'text',
                    ],
                    [
                        'attribute'=>'card_number',
                        'format'=>'text',
                    ],
                    [
                        'attribute'=>'month',
                        'format'=>'text',
                    ],
                    [
                        'attribute'=>'year',
                        'format'=>'text',
                    ],
                    [
                        'attribute'=>'sum',
                        'format'=>'raw',
                        'value'=> function ($model, $key, $index, $grid){

                            return ($model['sum'])? $model['sum']:0;
                        },
                        'label' =>'Сумма'
                    ],
                    [
                        'attribute'=>'updated_at',
                        'format'=>['date', 'php:d.m.Y'],
                        'filter' => \yii\jui\DatePicker::widget([
                            'options' => ['class' => 'form-control'],
                            'model' => $searchModel,
                            'attribute' => 'created_at',
                            'language' => 'ru',
                            'dateFormat' => 'dd.MM.yyyy',
                        ]),
                        'label' => 'Дата измененения данных по карте'
                    ],
                ];?>

                <p class="text-right">
                    <?= Html::a('Добавить карту', ['/create'], ['class' => 'btn btn-success']) ?>
                </p>

                <?echo \kartik\export\ExportMenu::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => $columns,
                    'exportConfig' => [
                        \kartik\export\ExportMenu::FORMAT_TEXT => false,
                        \kartik\export\ExportMenu::FORMAT_HTML => false,
                        \kartik\export\ExportMenu::FORMAT_EXCEL => false,
                        \kartik\export\ExportMenu::FORMAT_PDF =>  false,
                        \kartik\export\ExportMenu::FORMAT_CSV =>  false
                    ],

                ]);

                echo GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'options' => [
                        'class' => 'grid-view table-responsive'
                    ],
                    'tableOptions' => [
                        'class' => 'table table-striped table-bordered table-admin-event-to-users',
                    ],
                    'rowOptions'=> function ($model, $key, $index, $grid){
                        //if($model->application_status == 0){ return ['class'=>'new']; }
                    },
                    'columns' => $columns,
                ]); ?>

            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/preloader.php
<?php
/* @var $this yii\web\View */
$this->title = 'BMW EXCELLENCE CLUB';
?>
<div class="pl-topper">
    <div class="container">
        <div class="row">
            <div class="col-12 text-right">
                <div class="logo">
                    <a href="/" class="ls-wrapper">
                        <img src="/image/TransLoyd/logo1.png">
                        <div class="slogan">Trans Loyd</div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="pl-bottom">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="title">Trans Loyd <span class="d-md-none"><br></span> bank</div>
                <div class="text">
                    Банк <span class="d-md-none"><br></span> исключительных привилегий
                </div>

                <a href="/signin" class="sign">Продолжить</a>
            </div>
        </div>
    </div>
</div>

views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'Восстановление пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="preload-wrapper">
    <div class="backgrond"></div>

    <div class="pl-topper light">
        <div class="container">
            <div class="row">
                <div class="col-12 text-right">
                    <div class="logo">
                        <a href="/" class="ls-wrapper">
                            <img src="/image/TransLoyd/logo1.png">
                            <div class="slogan">Trans Loyd</div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="site-request-password-reset">
        <div class="row">
            <div class="col-lg-12">
                <div class="title">Восстановление пароля</div>

                <div class="text">Введите e-mail, указанный при регистрации.</div>


                <?php $form = ActiveForm::begin([
                    'id' => 'request-password-reset-form'
                ]); ?>

                    <?= $form->field($model, 'email')->textInput(['placeholder' => "E-mail"])->label(false);?>

                    <div class="form-group">
                        <?= Html::submitButton('Восстановить', ['class' => 'smb-btn'])?>
                    </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

</div>

views/site/requestWindowInner.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
$this->title = $pageTitle;
?>

<div class="site-request-window-inner <?= isset($class)? $class:'';?>">
    <div class="row">
        <div class="col-lg-12">
            <div class="title">
                <?= $title;?>
            </div>

            <div class="text">
                <?= $text;?>
            </div>

            <a class="btn-def" href="<?= $link;?>"><?= $linkText;?></a>
        </div>
    </div>
</div>